theme = "dark_plus"

[keys.normal]
G = "goto_file_end"          # vim
Z = { Z = ":wq", Q = ":q!" } # vim, save and quit, quit without saving
"#" = "toggle_comments"

[keys.normal.space]
w = ":write"

[keys.insert]
j = { k = "normal_mode" }

[keys.select]
G = "goto_file_end" # vim

[editor.cursor-shape]
insert = "bar" # change cursor shape in insert mode

[editor.file-picker]
hidden = false # don't ignore hidden files

[editor.statusline]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "selections",
  "position",
  "file-encoding",
] # add workspace-diagnostics

[editor.soft-wrap]
enable = true

# [editor]
# gutters = ["diagnostics", "spacer", "spacer", "diff"] # no line-numbers
