theme = "dark_plus"

[keys.normal]
G = "goto_file_end" # vim
Z = { Z = ":wq", Q = ":q!" } # vim
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"] # vim
"#" = "toggle_comments"

[keys.normal.space]
w = ":write"
l = ":toggle soft-wrap.enable"
i = ":toggle lsp.display-inlay-hints"
c = { r = ":sh kitty @ send-text --match 'title:^Terminal' cargo run \\\\n", t = ":sh kitty @ send-text --match 'title:^Terminal' 'clear \\ncargo test \\n'" }

[keys.insert]
j = { k = "normal_mode" }
C-backspace = "delete_word_backward"

[keys.select]
G = "goto_file_end" # vim

[editor.cursor-shape]
insert = "bar" # change cursor shape in insert mode

[editor.file-picker]
hidden = false # don't ignore hidden files

[editor.statusline]
center = ["version-control"]

[editor.soft-wrap]
enable = true
