# Use external tools for formatting

[[language]]
name = "bash"
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json"] }

[[language]]
name = "javascript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsx"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx"] }
auto-format = true

# Change or configure language servers

[[language]]
name = "git-commit"
language-server = { command = "ltex-ls" }

[[language]]
name = "markdown"
# language-server = { command = "ltex-ls" }
# config = { ltex.disabledRules = { "en-US" = [
#   "PROFANITY",
# ], "en-GB" = [
#   "PROFANITY",
# ] }, ltex.dictionary = { "en-US" = [
#   "builtin",
# ], "en-GB" = [
#   "builtin",
# ] } }
formatter = { command = 'prettier', args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "never",        # <always|never|preserve>
] }
# auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "rust"
[language.config]
cargo = { allFeatures = true }
checkOnSave = { command = "clippy" }
